<?php

define("FACEBOOK_APP_ID", "1035129189845262");
define("FACEBOOK_APP_SECRET", "1e121667b64b99f97148211d7df38a60");
define("FACEBOOK_APP_REDIRECT_URL", "http://localhost/drupal_task_1/user/test?social=facebook");

function facebook_entity_info() {
    $return = array(
        'facebook' => array(
            'label' => t('Facebook'),
            'entity class' => 'Facebook1',
            'controller class' => 'FacebookController',
            'base table' => 'facebook',
            'fieldable' => TRUE,
            'load hook' => 'facebook_load',
            'module' => 'facebook',
            'entity keys' => array(
                'id' => 'fid',
                'label' => ''
            ),
            'bundle keys' => array(
                'bundle' => 'name',
            ),
            'bundles' => array(),
            'view modes' => array(
                'full' => array(
                    'label' => t('Full'),
                    'custom settings' => FALSE,
                ),
                'admin' => array(
                    'label' => t('Admin'),
                    'custom settings' => TRUE,
                ),
            ),
            'label callback' => 'entity_class_label',
            'uri callback' => 'entity_class_uri',
        )
    );
    return $return;
}


function facebook_menu() {
    $items['admin/config/facebook'] = array(
        'title callback' => '',
        //'title arguments' => array('twitter', 1),
        'page callback' => 'facebook_page_view',
        //'page arguments' => array(1),
        //'access callback' => TRUE,
        'access arguments' => array('administer site configuration'),
        'file' => 'facebook.pages.inc',
    );
    return $items;
}

function facebook_load($twitter_id, $reset = FALSE) {
    $products = facebook_load_multiple(array($twitter_id), array(), $reset);
    return $products ? reset($products) : FALSE;
}

function facebook_load_multiple($product_ids = array(), $conditions = array(), $reset = FALSE) {
    return entity_load('facebook', $product_ids, $conditions, $reset);
}

function facebook_load_by_user() {
    global $user;
    $query = db_select('facebook', 'fb')
        ->fields('fb', array('fid'))
        ->condition('user_id', $user->uid);
    return $query->execute()->fetchField();
}

function facebook_get_auth_link() {
    $url = 'https://www.facebook.com/dialog/oauth';
    $params = array(
        'client_id'     => FACEBOOK_APP_ID,
        'redirect_uri'  => FACEBOOK_APP_REDIRECT_URL,
        'response_type' => 'code',
        'scope'         => 'publish_actions,user_posts'
    );
    return $url . '?' . urldecode(http_build_query($params));
}