<?php

function main_menu() {
    $items = [];
    $items['user/reg'] = array(
        'title' => 'Registration form',
        'page callback' => 'drupal_get_form',
        'access callback' => TRUE,
        'page arguments' => array('main_user_register_form')
    );
    $items['social'] = array(
        'title' => 'Social aggregator',
        'page callback' => 'main_page_callback',
        'access callback' => TRUE,
        'file' => 'main.pages.inc'
    );
    return $items;
}

function main_page_callback() {
    $module_path = drupal_get_path('module', 'main');
    $content = array(
        '#markup' => '',
        '#attached' => array(
            'js' => array(
                array('data' => $module_path . '/js/jquery.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/underscore.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/backbone.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/backbone.marionette.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/jquery.cookie.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app_config.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app_modeler.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app_viewer.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app_routing.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app_init.js', 'type' => 'file', 'scope' => 'footer')
            )
        )
    );
    $regForm = drupal_get_form('main_user_register_form');
    $regForm = drupal_render($regForm);
    $content['#markup'] = '
     <script type="text/template" id="notice-item"></script>
     <div id="menu"></div>
     <div id="spinner">
        <img src="' . $module_path . '/images/loading.gif" alt="Loading..." />
     </div>
     <div id="content-wrapper"></div>
     <script type="text/template" id="layout-template">
         <div id="noticeContainer"></div>
         <div id="mainContainer"></div>
     </script>
     <script type="text/template" id="auth-template">
         <div id="login-form">
            <form>
                <div class="form-item form-type-textfield form-item-login">
                    <label for="edit-name">Login <span title="This field is required." class="form-required">*</span></label>
                    <input type="text" class="form-text required" maxlength="15" size="30" value="" name="name" id="login-username">
                </div>
                <div class="form-item form-type-textfield form-item-login">
                    <label for="edit-pass">Password <span title="This field is required." class="form-required">*</span></label>
                    <input type="password" class="form-text required" maxlength="15" size="30" name="pass" id="login-password">
                </div>
                <p><input type="submit" class="form-submit" value="Log in" id="login-submit"></p>
            </form>
         </div>
         <div id="reg-form">' . $regForm . '</div>
     </script>
     <script type="text/template" id="list-template">
         <thead>
             <tr>
                 <th>Social name</th>
                 <th>Status</th>
             </tr>
         </thead>
         <tbody></tbody>
     </script>
     <script type="text/template" id="item-template">
         <td><%=name%></td>
         <td></td>
     </script>
     <script type="text/template" id="social-item-template">
         <div class="post-detail">
             <div class="content"><%=content%></div>
             <div class="date_post"><%=date_post%></div>
         </div>
     </script>
     <script type="text/template" id="social-list-template">
         <a class="close" href="#">Close x</a>
         <div class="user-name"></div>
         <div class="panel-new-post">
             <textarea placeholder="Text" class="text-new-post form-textarea" cols="100" rows="10"></textarea>
             <p><input class="add-new-post form-submit" value="Post"></p>
         </div>
         <div class="posts-wrapper"></div>
     </script>
     ';
    return $content;
}

function main_user_register_form($form, &$form_state) {
    $form['login'] = array(
        '#title' => 'Username',
        '#description' => '',
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#id' => 'reg-name'
    );
    $form['email'] = array(
        '#title' => 'Email',
        '#description' => '',
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 15,
        '#required' => TRUE,
        '#id' => 'reg-email'
    );
    $form['password'] = array(
        '#title' => 'Password',
        '#description' => '',
        '#type' => 'password',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#id' => 'reg-pass'
    );
    $form['password_approve'] = array(
        '#title' => 'Approve password',
        '#description' => '',
        '#type' => 'password',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
        '#id' => 'reg-approve-pass'
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#id' => 'reg-submit',
        '#value' => t('Sign up'),
    );
    return $form;
}

function main_user_register_form_validate($form, &$form_state) {
    if (!valid_email_address($form_state['values']['email'])) {
        form_set_error('email', t('Incorrect email format.'));
    }
    if ($form_state['values']['password'] != $form_state['values']['password_approve']) {
        form_set_error('password_approve', t('Passwords are not equal'));
        form_set_error('password', t('Passwords are not equal'));
    }
}

function main_user_register_form_submit($form, &$form_state){
    $newUser = array(
        'name' => $form_state['values']['login'],
        'pass' => $form_state['values']['password'],
        'mail' => $form_state['values']['email'],
        'init' => $form_state['values']['email'],
        'status' => 1,
        'access' => REQUEST_TIME,
        'created' => REQUEST_TIME
    );
    user_save(null, $newUser);
    drupal_set_message("Successful registration.");
}

function main_user_login_form($form, &$form_state) {
    $form['login'] = array(
        '#title' => 'Login',
        '#description' => '',
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
    );
    $form['password'] = array(
        '#title' => 'Password',
        '#description' => '',
        '#type' => 'password',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Sign in'),
    );
    return $form;
}

function main_services_resources() {
    return array(
        'social' => array(
            'index' => array(
                'help' => 'Retrieves a listing of socials',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_get_socials',
                'access arguments' => array('access content'),
                'args' => array(
                    array(
                        'name' => 'mode',
                        'type' => 'string',
                        'description' => '',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                ),
            ),
            'update' => array(
                'help' => 'Reset a social status',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_reset_social',
                'access arguments' => array('access content'),
                'args' => array(
                    array(
                        'name' => 'id',
                        'type' => 'int',
                        'description' => 'The id of the social to reset',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    )
                )
            )
        ),
        'post' => array(
            'index' => array(
                'help' => 'Retrieves a listing of posts',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_get_social_posts',
                'access arguments' => array('access content'),
                'args' => array(
                    array(
                        'name' => 'mode',
                        'type' => 'string',
                        'description' => 'The mode',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'typeSocial',
                        'type' => 'string',
                        'description' => 'The name of the selected social',
                        'source' => array('path' => '1'),
                        'optional' => FALSE,
                    ),
                ),
            ),
            'create' => array(
                'help' => 'Creates new post',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_public_post',
                'access arguments' => array('access content'),
                'args' => array(
                    array(
                        'name' => 'data',
                        'type' => 'struct',
                        'description' => 'Post data',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                ),
            )
        ),
        'auth' => array(
            'index' => array(
                'help' => 'Authorization user',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_auth_user',
                'access arguments' => array('access content'),
                'args' => array(
                    array(
                        'name' => 'mode',
                        'type' => 'string',
                        'description' => 'Mode',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                    array(
                         'name' => 'parameters',
                         'type' => 'array',
                         'description' => 'User parameters',
                         'source' => 'param',
                         'optional' => TRUE,
                         'default value' => array(),
                     )
                )
            ),
            'create' => array(
                'help' => 'Creates new user',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_auth_create_user',
                'access arguments' => array('access content'),
                'args' => array(
                    array(
                        'name' => 'data',
                        'type' => 'struct',
                        'description' => 'User data',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                ),
            )
        )
    );
}

function main_variable_info($options) {
    $variables['social_aggregator:BASE_URL_AUTH'] = array(
        'title' => t('Base url for authenticate', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => 'http://localhost/drupal_task_1/notes'
    );
    $variables['social_aggregator:FACEBOOK_APP_ID'] = array(
        'title' => t('Facebook application ID', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => '1640010319548174'
    );
    $variables['social_aggregator:FACEBOOK_APP_SECRET'] = array(
        'title' => t('Facebook application sercret', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => '7d64b5c69e9b6759bf781fb4a4868622'
    );
    $variables['social_aggregator:FACEBOOK_APP_REDIRECT_URL'] = array(
        'title' => t('Facebook application redirect url', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => 'http://localhost/drupal_task_1/social?social=facebook'
    );
    $variables['social_aggregator:INSTAGRAM_ID'] = array(
        'title' => t('Instagram application ID', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => '0a8c859217034967b1aec64ee5a1d9fc'
    );
    $variables['social_aggregator:INSTAGRAM_SECRET'] = array(
        'title' => t('Instagram application secret', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => '65bf77bcf7dc42d3b55e39b88e19b983'
    );
    $variables['social_aggregator:INSTAGRAM_CALLBACK'] = array(
        'title' => t('Instagram application redirect url', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => 'http://localhost/drupal_task_1/social?social=instagram'
    );
    $variables['social_aggregator:TWITTER_CONSUMER_KEY'] = array(
        'title' => t('Twitter application consumer key', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => 'Jt4lGWjVOJqvUalFyv911Dbkr'
    );
    $variables['social_aggregator:TWITTER_CONSUMER_SECRET'] = array(
        'title' => t('Twitter application consumer secret', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => 'LU32tiMn5NmCHzlfMTgFrmJjnPXsaaAfqQNTefdnoR1e3pcXqo'
    );
    $variables['social_aggregator:TWITTER_OAUTH_CALLBACK'] = array(
        'title' => t('Twitter application redirect url', array(), $options),
        'access' => 'administer',
        'type' => 'string',
        'default' => 'http://localhost/drupal_task_1/social?social=twitter'
    );
    return $variables;
}

function main_save_social_data($arrayData) {
    module_load_include('inc', 'main', 'main');
    _main_save_social_data($arrayData);
}