<?php

function main_menu() {
    $items = array();
    $items['user/reg'] = array(
        'title' => 'Registration form',
        'page callback' => 'drupal_get_form',
        'access callback' => TRUE,
        'page arguments' => array('main_user_register_form'),
    );
    $items['user/social/add'] = array(
        'title' => 'Add social accounts',
        'page callback' => 'social_add',
        //'access arguments' => array('administer site configuration'),
        'access callback' => TRUE,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
        'file' => 'social.pages.inc',
    );
    $items['user/test'] = array(
        'title' => 'home page',
        'page callback' => 'piy_page_callback',
        'access callback' => TRUE,
    );
    return $items;
}

function piy_page_callback() {
    $module_path = drupal_get_path('module', 'main');
    $content = array(
        '#markup' => '',
        '#attached' => array(
            // include backbone (underscore is automatically added as a dependency)
            //'libraries_load' => array(array('backbone')),
            // include our custom js and settings
            'js' => array(
                array('data' => $module_path . '/js/jquery.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/underscore.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/backbone.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/backbone.marionette.js', 'type' => 'file', 'scope' => 'footer'),
                array('data' => $module_path . '/js/app.js', 'type' => 'file', 'scope' => 'footer'),
            ),
            /*'css' => array(
                array('data' => $module_path . '/path/to/mybackboneapp.css', 'type' => 'file'),
            ),*/
        ),
    );
    //$layout = "http://localhost/drupal_task_1/" . $module_path . "/layout.tpl";
    //$item = "http://localhost/drupal_task_1/" . $module_path . "/item.tpl";
    $content['#markup'] = '
 <div id="content"></div>
<script type="text/template" id="layout-template">
<h1>Main Template</h1>
<div id="regionOne"></div>
</script>
<script type="text/template" id="item-template">
    <li><%=title%></li>
    <li><%=authorLast%></li>
    <li><%=authorFirst%></li>
</script>';
    return $content;
}

function main_settings_libraries_info() {
    $module_path = drupal_get_path('module', 'main');
    $libraries['underscore'] = array(
        'name' => 'underscore.js',
        'files' => array(
            'js' => array(
                //$module_path . '/js/underscore.js',
                'underscore.js',
            ),
        ),
    );
    $libraries['backbone'] = array(
        'name' => 'backbone.js',
        'files' => array(
            'js' => array(
                'backbone.js',
            ),
        ),
        'dependencies' => array(
            'underscore',
        ),
    );
    return $libraries;
}

function main_user_register_form($form, &$form_state) {
    $form['login'] = array(
        '#title' => 'Login',
        '#description' => '',
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
    );
    $form['email'] = array(
        '#title' => 'Email',
        '#description' => '',
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 15,
        '#required' => TRUE,
    );
    $form['password'] = array(
        '#title' => 'Password',
        '#description' => '',
        '#type' => 'password',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
    );
    $form['password_approve'] = array(
        '#title' => 'Approve password',
        '#description' => '',
        '#type' => 'password',
        '#size' => 30,
        '#maxlength' => 10,
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Sign up'),
    );
    return $form;
}

function main_user_register_form_validate($form, &$form_state) {
    if (!valid_email_address($form_state['values']['email'])) {
        form_set_error('email', t('Incorrect email format.'));
    }
    if ($form_state['values']['password'] != $form_state['values']['password_approve']) {
        form_set_error('password_approve', t('Passwords don\'t equal'));
        //form_set_error('password', t('Passwords don\'t. equal'));
    }
}

function main_user_register_form_submit($form, &$form_state){
    $newUser = array(
        'name' => $form_state['values']['login'],
        'pass' => $form_state['values']['password'],
        'mail' => $form_state['values']['email'],
        'init' => $form_state['values']['email'],
        'status' => 1,
        'access' => REQUEST_TIME,
        'created' => REQUEST_TIME
    );
    user_save(null, $newUser);
    drupal_set_message("Successful registration.");
}

function main_perm() {
    return array(
        'note resource create',
        'note resource view any note',
        'note resource view own notes',
        'note resource edit any note',
        'note resource edit own notes',
        'note resource delete any note',
        'note resource delete own notes',
    );
}

function main_get_note($id) {
    return (db_query("SELECT * FROM {note} WHERE id=:id", array(
        ':id' => $id,
    ))->fetchAssoc());
}

function main_write_note($note) {
    $primary_key = !empty($note->id) ? array('id') : NULL;
    drupal_write_record('note', $note, $primary_key);
}

function main_delete_note($id) {
    db_query("DELETE FROM {note} WHERE id=:id", array(
        ':id' => $id,
    ));
}

function main_services_resources() {
    return array(
        'note' => array(
            'retrieve' => array(
                'help' => 'Retrieves a note',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_retrieve',
                //'access callback' => '_main_access',
                //'access callback' => TRUE,
                //'access arguments' => array('administer site configuration'),
                //'access arguments' => array('view'),
                //'access arguments' => TRUE,
                //'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'id',
                        'type' => 'int',
                        'description' => 'The id of the note to get',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                ),
            ),
            'create' => array(
                'help' => 'Creates a note',
                'file' => array('file' => 'inc', 'module' => 'source'),
                'callback' => '_noteresource_create',
                'access arguments' => array('note resource create'),
                'access arguments append' => FALSE,
                'args' => array(
                    array(
                        'name' => 'data',
                        'type' => 'struct',
                        'description' => 'The note object',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                ),
            ),
            'update' => array(
                'help' => 'Updates a note',
                'file' => array('file' => 'inc', 'module' => 'source'),
                'callback' => '_noteresource_update',
                'access callback' => '_noteresource_access',
                'access arguments' => array('update'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'id',
                        'type' => 'int',
                        'description' => 'The id of the node to update',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                    array(
                        'name' => 'data',
                        'type' => 'struct',
                        'description' => 'The note data object',
                        'source' => 'data',
                        'optional' => FALSE,
                    ),
                ),
            ),
            'delete' => array(
                'help' => 'Deletes a note',
                'file' => array('file' => 'inc', 'module' => 'source'),
                'callback' => '_noteresource_delete',
                'access callback' => '_noteresource_access',
                'access arguments' => array('delete'),
                'access arguments append' => TRUE,
                'args' => array(
                    array(
                        'name' => 'nid',
                        'type' => 'int',
                        'description' => 'The id of the note to delete',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                ),
            ),
            'index' => array(
                'help' => 'Retrieves a listing of notes',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_index',
                'access callback' => '_main_access',
                'access arguments' => array('access content'),
                'access arguments append' => FALSE,
                'args' => array(
                    array(
                        'name' => 'page',
                        'type' => 'int',
                        'description' => '',
                        'source' => array(
                            'param' => 'page',
                        ),
                        'optional' => TRUE,
                        'default value' => 0,
                    ),
                    array(
                        'name' => 'parameters',
                        'type' => 'array',
                        'description' => '',
                        'source' => 'param',
                        'optional' => TRUE,
                        'default value' => array(),
                    ),
                ),
            ),
        ),
        'social' => array(
            /*'relationships' => array(
                'get_socials' => array(
                    'help' => 'Retrieves a listing of notes',
                    'file' => array('file' => 'inc', 'module' => 'main'),
                    'callback' => '_main_get_socials',
                    'access arguments' => array('administer site configuration'),
                )
            ),
            'actions' => array(
                'get_socials1' => array(
                    'help' => 'Retrieves a listing of notes',
                    'file' => array('file' => 'inc', 'module' => 'main'),
                    'callback' => '_main_get_socials',
                    'access arguments' => array('administer site configuration'),
                )
            ),*/
            'index' => array(
                'help' => 'Retrieves a listing of notes',
                'file' => array('file' => 'inc', 'module' => 'main'),
                'callback' => '_main_get_socials',
                'access arguments' => array('administer site configuration'),
                //'args' => array()
                'args' => array(
                    array(
                        'name' => 'mode',
                        'type' => 'string',
                        'description' => '',
                        'source' => array('path' => '0'),
                        'optional' => FALSE,
                    ),
                ),
            )
        )
    );
}

function getSocials() {
    //var_dump(getTwitterAccount());die;
    $arr = [];
    $arr['twitter'] = getTwitterAccount();
    $arr['facebook'] = true;
    $arr['instagram'] = false;
    return $arr;
}

function getFacebookAccount() {

}

/*function getTwitterAccount() {
    return twitter_load_by_user();
}*/

function getInstagramAccount() {

}