<?php

require "twitter_api/autoload.php";
use Abraham\TwitterOAuth\TwitterOAuth;

define("TWITTER_CONSUMER_KEY", "Jt4lGWjVOJqvUalFyv911Dbkr");
define("TWITTER_CONSUMER_SECRET", "LU32tiMn5NmCHzlfMTgFrmJjnPXsaaAfqQNTefdnoR1e3pcXqo");
define("TWITTER_OAUTH_CALLBACK", "http://localhost/drupal_task_1/social?social=twitter");

function twitter_entity_info() {
    $return = array(
        'twitter' => array(
            'label' => t('Twitter'),
            'entity class' => 'Twitter',
            'controller class' => 'TwitterController',
            'base table' => 'twitter',
            'fieldable' => TRUE,
            'load hook' => 'twitter_load',
            'module' => 'twitter',
            'entity keys' => array(
                'id' => 'tid',
                'label' => ''
            ),
            'bundle keys' => array(
                'bundle' => 'name',
            ),
            'bundles' => array(),
            'view modes' => array(
                'full' => array(
                    'label' => t('Full'),
                    'custom settings' => FALSE,
                ),
                'admin' => array(
                    'label' => t('Admin'),
                    'custom settings' => TRUE,
                ),
            ),
            'label callback' => 'entity_class_label',
            'uri callback' => 'entity_class_uri',
        )
    );
    return $return;
}


function twitter_menu() {
    $items['admin/config/twitter/%twitter'] = array(
        'title callback' => 'entity_label',
        //'title arguments' => array('twitter', 1),
        'page callback' => 'twitter_page_view',
        'page arguments' => array(1),
        //'access callback' => TRUE,
        'access arguments' => array('administer site configuration'),
        'file' => 'twitter.pages.inc',
    );
    $items['admin/config/twitter'] = array(
        'title callback' => '',
        //'title arguments' => array('twitter', 1),
        'page callback' => 'twitter_page_view',
        //'page arguments' => array(1),
        //'access callback' => TRUE,
        'access arguments' => array('administer site configuration'),
        'file' => 'twitter.pages.inc',
    );
    return $items;
}

function twitter_load($twitter_id, $reset = FALSE) {
    $products = twitter_load_multiple(array($twitter_id), array(), $reset);
    return $products ? reset($products) : FALSE;
}

function twitter_load_multiple($product_ids = array(), $conditions = array(), $reset = FALSE) {
    return entity_load('twitter', $product_ids, $conditions, $reset);
}

function twitter_load_by_user() {
    global $user;
    $query = db_select('twitter', 'tw')
        ->fields('tw', array('tid'))
        ->condition('user_id', $user->uid);
    return $query->execute()->fetchField();
}

function twitter_get_auth_link() {
    $connection = new TwitterOAuth(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET);
    $request_token = $connection->oauth('oauth/request_token', array('oauth_callback' => TWITTER_OAUTH_CALLBACK));
    $link = $connection->url('oauth/authorize', array('oauth_token' => $request_token['oauth_token']));
    $_SESSION['oauth_token'] = $request_token['oauth_token'];
    $_SESSION['oauth_token_secret'] = $request_token['oauth_token_secret'];
    return $link;
}

function twitter_reset($id) {
    global $user;
    return db_delete('twitter')
        ->condition('user_id', $user->uid)
        ->condition('tid', $id)
        ->execute();
}

function twitter_get_posts() {
    global $user;
    $twitterData = db_select('twitter', 'tw')
        ->fields('tw', array('oauth_token', 'oauth_token_secret'))
        ->condition('user_id', $user->uid)
        ->execute()
        ->fetchObject();
    $connection = new TwitterOAuth(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, $twitterData->oauth_token, $twitterData->oauth_token_secret);
    $twits = $connection->get("statuses/user_timeline");
    $parsedActualTwits = [];
    foreach($twits as $index => $twit) {
        $date = new DateTime($twit->created_at);
        $formattedDate = $date->format('d/m/Y');
        $parsedActualTwits[$index]['date_post'] = $formattedDate;
        $parsedActualTwits[$index]['content'] = $twit->text;
    }
    //var_dump($parsedActualTwits);die;
    return $parsedActualTwits;
}

function twitter_public_post($data) {
    global $user;
    $twitterData = db_select('twitter', 'tw')
        ->fields('tw', array('oauth_token', 'oauth_token_secret'))
        ->condition('user_id', $user->uid)
        ->execute()
        ->fetchObject();
    $connection = new TwitterOAuth(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET, $twitterData->oauth_token, $twitterData->oauth_token_secret);
    $connection->post('statuses/update', array('status' => $data->content));
    if ($connection->getLastHttpCode() == 200) {
        return true;
    } else {
        return $connection->getLastHttpCode();
    }
    //return true;
}